{"uuid":"1546e6e1-6e54-457f-8e76-0756b1520f20","historyId":"3b6de4106b144f3a4012ff7abbaea49","fullName":"ru.yandex.practicum.scooter.CourierCreatingTest.twoSameCouriersCanNotBeCreated","labels":[{"name":"package","value":"ru.yandex.practicum.scooter"},{"name":"testClass","value":"ru.yandex.practicum.scooter.CourierCreatingTest"},{"name":"testMethod","value":"twoSameCouriersCanNotBeCreated"},{"name":"suite","value":"ru.yandex.practicum.scooter.CourierCreatingTest"},{"name":"host","value":"WGD02RTI1924"},{"name":"thread","value":"14408@WGD02RTI1924.main(1)"},{"name":"framework","value":"junit4"},{"name":"language","value":"java"}],"links":[],"name":"Check status code and message of POST /api/v1/courier","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Тело ответа не соответствует: expected:<...гин уже используется[]> but was:<...гин уже используется[. Попробуйте другой.]>","trace":"org.junit.ComparisonFailure: Тело ответа не соответствует: expected:<...гин уже используется[]> but was:<...гин уже используется[. Попробуйте другой.]>\r\n\tat org.junit.Assert.assertEquals(Assert.java:117)\r\n\tat ru.yandex.practicum.scooter.CourierCreatingTest.twoSameCouriersCanNotBeCreated(CourierCreatingTest.java:101)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\r\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)\r\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\r\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)\r\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\r\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\r\n\tat org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)\r\n\tat org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)\r\n\tat org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)\r\n\tat org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)\r\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)\r\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)\r\n\tat org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)\r\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)\r\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)\r\n\tat org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)\r\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)\r\n\tat org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)\r\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:413)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)\r\n"},"stage":"finished","description":"Negative test for POST /api/v1/courier with invalid courier with existent login","steps":[],"attachments":[],"parameters":[],"start":1676924300766,"stop":1676924300991}